apiVersion: v1
kind: Service
metadata:
  name: lp-budget-service
spec:
  selector:
    app: lp-budget
  ports:
  - port: 6000
    targetPort: 5000
    nodePort: 30000
  type: NodePort

---
apiVersion: v1
kind: Pod
metadata:
  name: lp-budget
  labels:
    app: lp-budget
spec:
  containers:
    - name: lp-budget
      image: brbursey/lp-budget:latest
      ports:
        - containerPort: 6000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lp-budget
spec:
  selector:
    matchLabels:
      app: lp-budget
  replicas: 4
  template:
    metadata:
      labels:
        app: lp-budget
    spec:
      containers:
      - name: lp-budget
        image: brbursey/lp-budget:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000